[client]
showSidebarNavigation = false
toolbarMode = "minimal"
showErrorDetails = "none"

[browser]
gatherUsageStats = false

[server]
headless = true
enableStaticServing = true
runOnSave = true

[theme]
base="light"

primaryColor="#BFA75F"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F6F8FC"
textColor="#222222"
font = "sans serif"